### ISSUE TITLE
Uncaught TypeError: Cannot read property 'deserialize' of undefined

### ISSUE THREAD

**Issue by fcrisciani** [benwbooth/atom-persistent-undo#6]
[Enter steps to reproduce:]

1. open project

**Atom**: 1.21.0-beta1 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [persistent-undo](https://github.com/benwbooth/atom-persistent-undo) package 1.2.0

### Stack Trace

Uncaught TypeError: Cannot read property 'deserialize' of undefined

```
At .atom/packages/persistent-undo/lib/persistent-undo.coffee:35

TypeError: Cannot read property 'deserialize' of undefined
    at /packages/persistent-undo/lib/persistent-undo.coffee:35:36
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:416:3)
```

### Commands

```
     -0:22.7.0 project-manager:list-projects (input.hidden-input)
     -0:20.9.0 editor:consolidate-selections (input.hidden-input)
     -0:20.9.0 core:cancel (input.hidden-input)
     -0:20.1.0 project-manager:list-projects (input.hidden-input)
     -0:18.9.0 core:move-down (input.hidden-input)
     -0:18.6.0 core:confirm (input.hidden-input)
     -0:18.5.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:15.6.0 fuzzy-finder:toggle-file-finder (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:13.4.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.5 
atom-typescript 11.0.9 
auto-update-packages 1.0.1 
busy-signal 1.4.3 
file-icons 2.1.12 
git-blame 1.2.2 
git-history 3.3.0 
git-time-machine 1.5.9 
go-debug 1.5.2 
go-outline 0.6.6 
go-plus 5.5.5 
go-signature-statusbar 1.2.3 
hey-pane 1.0.0 
highlight-selected 0.13.1 
hyperclick 0.1.5 
intentions 1.1.5 
language-protobuf 0.7.1 
last-cursor-position 0.9.2 
linter 2.2.0 
linter-ui-default 1.6.10 
minimap 4.29.7 
minimap-cursorline 0.2.0 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-linter 2.1.0 
minimap-selection 4.5.0 
minimap-split-diff 0.3.7 
persistent-undo 1.2.0 
project-manager 3.3.5 
split-diff 1.5.1 
sync-settings 0.8.3 
```

**Comment by pthrasher** [comment]
[Enter steps to reproduce:]

1. Open project or Open first file in project after all tabs had been closed.


**Atom**: 1.21.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [persistent-undo](https://github.com/benwbooth/atom-persistent-undo) package 1.2.0


### Stack Trace

Uncaught TypeError: Cannot read property 'deserialize' of undefined

```
At /Users/philip.thrasher/.homesick/repos/thrash/home/.atom/packages/persistent-undo/lib/persistent-undo.coffee:35

TypeError: Cannot read property 'deserialize' of undefined
    at /packages/persistent-undo/lib/persistent-undo.coffee:35:36
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:416:3)
```

### Commands

```
     -1:19.2.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
     -1:15.2.0 settings-view:open (div.panels-item)
```

### Non-Core Packages

```
aligner 1.2.4 
aligner-javascript 1.3.0 
atom-ide-ui 0.4.0 
atom-material-ui 2.0.4 
atom-mermaid 3.1.0 
atom-wallaby 1.0.20 
bookmarklet 0.7.1 
cursor-history 0.12.0 
duotone-dark-sky-syntax 2.1.0 
duotone-dark-syntax 2.1.0 
earthsung-syntax-atom 2.0.0 
editorconfig 2.2.2 
elmjutsu 6.0.0 
file-icons 2.1.12 
git-time-machine 1.5.9 
haskell-grammar 0.4.0 
highlight-selected 0.13.1 
ide-flowtype 0.17.4 
language-babel 2.75.0 
language-docker 1.1.8 
language-elm 1.5.0 
language-fish-shell 1.0.5 
language-graphql 0.9.0 
language-groovy 0.7.0 
language-ini 1.19.0 
language-lua 0.9.11 
language-mermaid 0.6.0 
language-ocaml 1.9.5 
language-opencl 0.1.1 
language-rust 0.4.12 
language-swift 0.5.0 
language-thrift 1.0.2 
linter-eslint 8.3.2 
linter-rust 0.8.0 
MagicPython 1.0.12 
markdown-preview-plus 2.4.10 
material-ui 1.0.10 
merge-conflicts 1.4.5 
nice-index 1.0.5 
nord-atom-syntax 0.9.1 
nord-atom-ui 0.11.0 
persistent-undo 1.2.0 
pigments 0.40.2 
pretty-json 1.6.4 
pristine-ui 1.1.10 
set-syntax 0.4.0 
solarized-dark-ui 0.3.2 
solarized-light-ui 0.1.0 
sort-lines 0.15.0 
sort-words 0.1.2 
tool-bar 1.1.0 
vim-mode-plus 1.8.1 
wakatime 7.0.3 
zentabs 0.8.8 
```

**Comment by kirley** [comment]
i just had this issue too.

**Comment by jrial** [comment]
Happened to me after updating to Atom 1.21.0 and restarting. Didn't happen when restarting a couple of minutes ago before updating Atom.

I notice everyone in this thread seems to be running 1.21.0 or a 1.21 beta, so my guess is something in Atom changed to cause this.

[Enter steps to reproduce:]

1. Update to Atom 1.21.0
2. Restart Atom

**Atom**: 1.21.0 x64
**Electron**: 1.6.9
**OS**: Linux Mint
**Thrown From**: [persistent-undo](https://github.com/benwbooth/atom-persistent-undo) package 1.2.0


### Stack Trace

Uncaught TypeError: Cannot read property 'deserialize' of undefined

```
At /home/nighty/.atom/packages/persistent-undo/lib/persistent-undo.coffee:35

TypeError: Cannot read property 'deserialize' of undefined
    at /packages/persistent-undo/lib/persistent-undo.coffee:35:36
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:416:3)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.30.5 
atom-cli-diff 1.9.0 
atom-django 0.3.2 
atom-meld 0.3.5 
atom-python-virtualenv 0.14.0 
atom-transpose 0.3.4 
autocomplete-python 1.10.3 
blame 0.12.0 
busy-signal 1.4.3 
custom-title 1.0.1 
data-atom 0.26.0 
DjangoRAD 0.0.1 
emmet 2.4.3 
emmet-snippets-compatibility 1.0.6 
file-watcher 1.2.6 
git-plus 7.9.3 
git-time-machine 1.5.9 
hyperclick 0.1.5 
indent-guide-improved 1.4.13 
intentions 1.1.5 
language-django 0.1.1 
language-nginx 0.8.0 
linter 2.2.0 
linter-pycodestyle 2.1.3 
linter-pylint 2.1.0 
linter-ui-default 1.6.10 
local-history 4.3.0 
merge-conflicts 1.4.5 
minimap 4.29.7 
minimap-linter 2.1.1 
monokai 0.24.0 
open-html-in-browser 0.2.0 
open-terminal-here 2.3.1 
persistent-undo 1.2.0 
project-manager 3.3.5 
python-tools 0.6.9 
selection-highlight 0.1.6 
sort-lines 0.15.0 
symbols-tree-view 0.14.0 
tag 0.5.0 
termination 0.6.1 
up2date 0.1.2 
Zen 0.18.0 
```

**Comment by jrial** [comment]
UPDATE: it appears this bug also prevents us from saving our work. I noticed I couldn't save the file I've been working on today, not even after disabling this package. I had to disable the package, then restart Atom, before I was able to save anything again. Upon enabling, I got this error, and saving was again impossible.

Clarification:

- Saving will fail silently. No error pops up, but the editor still marks the file as dirty. When trying to close the file, a popup appears, alerting you to the unsaved contents. Trying to save from within this dialog will also fail.
- This bug doesn't seem to interfere with Atom's "persist dirty buffers" feature. Upon restarting, you're presented with the unsaved contents, and the file is still marked as dirty.
- When saving existing files, the on-disk contents do not change.
- When creating a new file and filling with content, the file gets created on-disk, but remains empty.

**Comment by clessg** [comment]
I believe this can be fixed by changing `editor.buffer.history` to `editor.buffer.historyProvider`

https://github.com/benwbooth/atom-persistent-undo/blob/master/lib/persistent-undo.coffee#L22

https://github.com/benwbooth/atom-persistent-undo/blob/master/lib/persistent-undo.coffee#L35

**Comment by benwbooth** [comment]
@clessg thanks for the tip. I just pushed a new version with the fix and it looks like it works.

**Comment by casalaina** [comment]
@benwbooth, I'm seeing both those changes in the coffee file after an update but I'm still getting the error, which then triggers a series of other errors (like [this](https://github.com/atom/atom/issues/14461)). Unless I'm missing something, you might want to unclose and investigate further. Removing persistent-undo from the packages folder fixed the issue.

**Comment by jrial** [comment]
@casalaina Can you confirm that reinstalling persistent-undo brings back these errors? I've updated and re-enabled the package, and for me the problems have disappeared.

**Comment by casalaina** [comment]
Ah, @jrial you're correct, a simple reinstall did the trick. Thanks.

**Comment by ongmin** [comment]
reinstall reintroduced the error for me, I just uninstalled persistent-undo altogether.
